name: ci
on:
  push:
    branches:
      - main
  pull_request:
env:
  # Path to where test results will be saved.
  TEST_RESULTS: /tmp/test-results
  # Default minimum version of Go to support.
  DEFAULT_GO_VERSION: 1.15
jobs:
  compatibility-test:
    strategy:
      matrix:
        go-version: [1.16, 1.15]
        os: [ubuntu-latest, macos-latest]
        # GitHub Actions does not support arm* architectures on default
        # runners. It is possible to acomplish this with a self-hosted runner
        # if we want to add this in the future:
        # https://docs.github.com/en/actions/hosting-your-own-runners/using-self-hosted-runners-in-a-workflow
        arch: ["386", amd64]
        exclude:
        # Not a supported Go OS/architecture.
        - os: macos-latest
          arch: "386"
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Environment
      run: |
        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
      shell: bash
    - name: Module cache
      uses: actions/cache@v2.1.5
      env:
        cache-name: go-mod-cache
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/go.sum') }}
    - name: Run tests
      env:
        GOARCH: ${{ matrix.arch }}
      run: make test-short
